// app/birthday/phrases.ts
export const phrases = [
// === AMOR Y CARIÑO (50) ===
"Te amo con todo mi corazón ❤️",
"Eres el amor de mi vida 💑",
"Mi corazón late por ti 💓",
"Cada día te amo más 💘",
"Mi amor por ti crece sin límites 🌱",
"Eres mi felicidad constante ☀️",
"Tu amor ilumina mis días 💫",
"Eres mi razón de sonreír 😊",
"Contigo todo es perfecto 💝",
"Mi corazón te pertenece 💖",
"Eres mi mejor aventura 🌈",
"Tu amor me hace mejor persona 🦋",
"Eres mi sueño hecho realidad ✨",
"Mi amor por ti es infinito 💫",
"Juntos somos invencibles 💪",
"Eres mi amor eterno 💘",
"Tu amor me hace feliz 🌟",
"Eres mi todo 💑",
"Mi corazón es tuyo 💓",
"Contigo la vida es bella 🌸",
"Eres mi amor verdadero 💕",
"Tu amor me completa 💖",
"Eres mi destino 🌟",
"Mi amor por ti es puro 💝",
"Juntos hasta el infinito ⭐",
"Eres mi amor perfecto 💘",
"Tu amor me inspira 💫",
"Eres mi mejor regalo 🎁",
"Mi corazón te eligió 💓",
"Contigo todo es posible 🌈",
"Eres mi amor soñado 💕",
"Tu amor me hace fuerte 💪",
"Eres mi felicidad completa ☀️",
"Mi amor por ti es eterno 💖",
"Juntos somos uno 💑",
"Eres mi amor infinito 💘",
"Tu amor me transforma 🦋",
"Eres mi mejor historia 📖",
"Mi corazón te anhela 💓",
"Contigo soy feliz 😊",
"Eres mi amor verdadero 💕",
"Tu amor me llena de vida 🌱",
"Eres mi destino perfecto 🌟",
"Mi amor por ti crece cada día 💖",
"Juntos hacemos magia ✨",
"Eres mi amor eterno 💘",
"Tu amor me hace mejor 💫",
"Eres mi razón de vivir 💝",
"Mi corazón te pertenece 💓",
"Contigo todo es especial 🌸",

// === CUMPLEAÑOS (50) ===
"¡Feliz cumpleaños, hermosa! 🎉",
"Que este día sea mágico ✨",
"Celebrando tu vida con alegría 🎈",
"Hoy es tu día especial 👑",
"Que todos tus deseos se cumplan 🌟",
"Un año más de bendiciones 🙏",
"Celebrando tu existencia 🎊",
"Que la felicidad te acompañe siempre 🌈",
"Brindando por ti hoy y siempre 🥂",
"Que este nuevo año te traiga todo lo que deseas 💫",
"Feliz vuelta al sol 🌞",
"Celebrando tu día con amor 💝",
"Que este año sea inolvidable 🎁",
"Festejando tu vida 🎊",
"Que cumplas muchos más 🎂",
"Hoy el cielo está de fiesta 🌟",
"Un año más de alegría 😊",
"Celebrando tu luz ✨",
"Que este día sea perfecto 🎈",
"Felicidades en tu día 🎉",
"Que la vida te sonría siempre 😊",
"Celebrando tu existencia 🌟",
"Un año más de felicidad 💝",
"Que este día sea especial 🎊",
"Feliz nuevo año de vida 🎈",
"Celebrando tu presencia 💫",
"Que este día sea memorable 🎁",
"Feliz cumpleaños, princesa 👑",
"Que la vida te sorprenda 🌈",
"Un año más de bendiciones 🙏",
"Celebrando tu día especial 🎉",
"Que este año sea maravilloso ✨",
"Feliz vuelta al sol, hermosa 🌞",
"Celebrando tu alegría 😊",
"Que este día sea único 🎈",
"Feliz cumpleaños, reina 👑",
"Que la vida te llene de amor 💝",
"Un año más de sueños cumplidos 🌟",
"Celebrando tu felicidad 🎊",
"Que este día sea mágico ✨",
"Feliz nuevo comienzo 🎈",
"Celebrando tu luz interior 💫",
"Que este año sea extraordinario 🎁",
"Feliz cumpleaños, ángel 👼",
"Que la vida te sonría siempre 😊",
"Un año más de aventuras 🌈",
"Celebrando tu existencia única 🎉",
"Que este día sea inolvidable ✨",
"Feliz vuelta al sol, preciosa 🌞",
"Celebrando tu día con amor 💝",

// === MOTIVACIÓN (50) ===
"Eres increíble en todo lo que haces 💪",
"Tu fuerza interior es admirable 🔥",
"Eres capaz de lograr lo que te propongas 🎯",
"Tu energía es contagiosa ⚡",
"Inspiras a quienes te rodean 🌟",
"Tu determinación es asombrosa 💫",
"Eres imparable 🚀",
"Tu potencial es infinito ✨",
"Nada puede detenerte 💪",
"Eres una guerrera invencible ⚔️",
"Tu valentía es inspiradora 🦁",
"Eres más fuerte de lo que crees 💪",
"Tu perseverancia te llevará lejos 🎯",
"Eres una luchadora incansable 💫",
"Tu fuerza es admirable 🔥",
"Eres capaz de todo 🌟",
"Tu determinación es tu poder ⚡",
"Eres una triunfadora 🏆",
"Tu éxito es inevitable 💫",
"Eres extraordinaria en todo 👑",
"Tu poder interior es único 💪",
"Eres una líder natural 🌟",
"Tu fortaleza es inspiradora 🔥",
"Eres invencible 💫",
"Tu determinación te hace única ⭐",
"Eres una guerrera de luz ✨",
"Tu valentía es tu escudo 🛡️",
"Eres más fuerte cada día 💪",
"Tu perseverancia es admirable 🎯",
"Eres una luchadora nata ⚔️",
"Tu fuerza interior brilla 🌟",
"Eres capaz de todo lo que sueñas 💫",
"Tu determinación mueve montañas 🏔️",
"Eres una triunfadora innata 🏆",
"Tu éxito está asegurado ⭐",
"Eres extraordinaria siempre 👑",
"Tu poder no tiene límites 💪",
"Eres una líder inspiradora 🌟",
"Tu fortaleza es tu mejor arma 🔥",
"Eres invencible en la adversidad 💫",
"Tu determinación es tu guía ⭐",
"Eres una guerrera de corazón ❤️",
"Tu valentía es legendaria 🦁",
"Eres más fuerte que ayer 💪",
"Tu perseverancia es tu virtud 🎯",
"Eres una luchadora ejemplar ⚔️",
"Tu fuerza interior es tu poder 🌟",
"Eres capaz de alcanzar las estrellas 💫",
"Tu determinación es inquebrantable 💪",
"Eres una triunfadora por naturaleza 🏆",

// === ALEGRÍA Y FELICIDAD (50) ===
"Tu alegría es contagiosa 😄",
"Tu sonrisa ilumina el mundo 😊",
"Eres pura felicidad 🌞",
"Tu risa es música para mis oídos 🎵",
"Irradias alegría por donde vas ✨",
"Tu felicidad llena espacios 🌈",
"Eres un rayito de sol ☀️",
"Tu alegría es mi motivación 😊",
"Eres la felicidad personificada 💫",
"Tu sonrisa es mágica ✨",
"Irradias luz propia 🌟",
"Tu alegría es un regalo 🎁",
"Eres felicidad pura 😊",
"Tu risa es contagiosa 😄",
"Iluminas cada espacio 💫",
"Tu felicidad es inspiradora 🌈",
"Eres un sol radiante ☀️",
"Tu alegría es bendición 🙏",
"Eres luz en la oscuridad ✨",
"Tu sonrisa es esperanza 💫",
"Irradias felicidad genuina 🌟",
"Tu alegría es un tesoro 💎",
"Eres felicidad andante 😊",
"Tu risa es medicina 💊",
"Iluminas vidas 🌞",
"Tu felicidad es contagiosa 🌈",
"Eres un ángel de alegría 👼",
"Tu alegría es un don 🎁",
"Eres luz brillante ✨",
"Tu sonrisa es vida 💫",
"Irradias amor y alegría ❤️",
"Tu felicidad es única 🌟",
"Eres alegría pura 😊",
"Tu risa es melodía 🎵",
"Iluminas corazones 💖",
"Tu felicidad es mágica ✨",
"Eres un sol de alegría ☀️",
"Tu alegría es bendita 🙏",
"Eres luz infinita 💫",
"Tu sonrisa es poder 💪",
"Irradias felicidad sincera 🌟",
"Tu alegría es contagiosa 😄",
"Eres felicidad viva 🌈",
"Tu risa es alegría pura 😊",
"Iluminas el camino ✨",
"Tu felicidad es luz 💫",
"Eres un ángel de luz 👼",
"Tu alegría es vida 🌟",
"Eres luz eterna ✨",
"Tu sonrisa es magia pura 💫",

// === ADMIRACIÓN (50) ===
"Te admiro profundamente 🌟",
"Eres mi ejemplo a seguir 💫",
"Tu inteligencia me asombra 🧠",
"Eres increíblemente talentosa 🎯",
"Tu dedicación es admirable 📚",
"Eres una inspiración constante ✨",
"Tu sabiduría es extraordinaria 🎓",
"Eres un modelo a seguir 👑",
"Tu talento es único 🌟",
"Eres extraordinariamente capaz 💪",
"Tu inteligencia brilla 💫",
"Eres un ejemplo de excelencia ⭐",
"Tu dedicación inspira 📖",
"Eres una líder natural 👑",
"Tu sabiduría guía 🌟",
"Eres un faro de luz ✨",
"Tu talento es excepcional 🎯",
"Eres admirablemente fuerte 💪",
"Tu inteligencia cautiva 🧠",
"Eres un ejemplo de perseverancia 💫",
"Tu dedicación es única 📚",
"Eres una inspiración diaria ⭐",
"Tu sabiduría ilumina 🌟",
"Eres un modelo de éxito 👑",
"Tu talento resplandece ✨",
"Eres extraordinariamente brillante 💫",
"Tu inteligencia sorprende 🧠",
"Eres un ejemplo de superación 💪",
"Tu dedicación motiva 📖",
"Eres una líder inspiradora 👑",
"Tu sabiduría transforma 🌟",
"Eres un faro de esperanza ✨",
"Tu talento es admirable 🎯",
"Eres admirablemente resiliente 💪",
"Tu inteligencia inspira 🧠",
"Eres un ejemplo de fortaleza 💫",
"Tu dedicación es ejemplar 📚",
"Eres una inspiración constante ⭐",
"Tu sabiduría es luz 🌟",
"Eres un modelo de excelencia 👑",
"Tu talento es extraordinario ✨",
"Eres extraordinariamente única 💫",
"Tu inteligencia es un don 🧠",
"Eres un ejemplo de determinación 💪",
"Tu dedicación es increíble 📖",
"Eres una líder excepcional 👑",
"Tu sabiduría es invaluable 🌟",
"Eres un faro de inspiración ✨",
"Tu talento es un regalo 🎯",
"Eres admirablemente valiente 💪",

// === GRATITUD (50) ===
"Gracias por ser parte de mi vida 🙏",
"Agradezco cada momento contigo 💫",
"Eres una bendición 🌟",
"Gracias por tu amor incondicional ❤️",
"Valoro cada instante a tu lado ⭐",
"Eres mi mayor gratitud 🙏",
"Gracias por existir ✨",
"Bendito el día que llegaste 🌅",
"Eres mi mayor tesoro 💎",
"Gracias por tanto amor 💝",
"Agradezco tu presencia 🌟",
"Eres un regalo del cielo 👼",
"Gracias por tu luz ✨",
"Valoro tu amistad 🤝",
"Eres una bendición diaria 🙏",
"Gracias por tu bondad ❤️",
"Agradezco tu compañía 💫",
"Eres un milagro 🌟",
"Gracias por tu paciencia 🕊️",
"Valoro tu cariño 💝",
"Eres mi gratitud infinita 🙏",
"Gracias por tu apoyo ✨",
"Agradezco tu sinceridad 💫",
"Eres un ángel guardián 👼",
"Gracias por tu comprensión ❤️",
"Valoro tu lealtad 🤝",
"Eres una bendición única 🌟",
"Gracias por tu generosidad 🎁",
"Agradezco tu fortaleza 💪",
"Eres un regalo divino ✨",
"Gracias por tu dulzura 🍯",
"Valoro tu amistad sincera 🤗",
"Eres mi mayor alegría 😊",
"Gracias por tu bondad infinita ❤️",
"Agradezco tu presencia diaria 🌟",
"Eres una luz en mi camino ✨",
"Gracias por tu amor puro 💝",
"Valoro cada momento juntos ⭐",
"Eres mi bendición constante 🙏",
"Gracias por tu paciencia infinita 🕊️",
"Agradezco tu compañía eterna 💫",
"Eres un milagro en mi vida 🌟",
"Gracias por tu apoyo incondicional 💪",
"Valoro tu sinceridad absoluta 💫",
"Eres un ángel en mi vida 👼",
"Gracias por tu comprensión total ❤️",
"Agradezco tu lealtad eterna 🤝",
"Eres una bendición especial 🌟",
"Gracias por tu generosidad infinita 🎁",
"Valoro tu fortaleza inspiradora 💪",

// === DESEOS Y BENDICIONES (50) ===
"Que la vida te sonría siempre 😊",
"Que tus sueños se hagan realidad 💫",
"Que cada día sea especial ✨",
"Que la felicidad te persiga 🌈",
"Que el amor te rodee siempre ❤️",
"Que la suerte sea tu compañera 🍀",
"Que la vida te sorprenda gratamente 🎁",
"Que tus días estén llenos de luz ☀️",
"Que la alegría nunca falte 🎈",
"Que todos tus deseos se cumplan 🌠",
"Que la paz te acompañe 🕊️",
"Que el éxito te persiga 🏆",
"Que la salud sea tu aliada 💪",
"Que el amor te encuentre 💘",
"Que la fortuna te sonría 🎰",
"Que tus sueños vuelen alto 🦋",
"Que la vida te bendiga 🙏",
"Que la felicidad sea tuya 😊",
"Que el amor te guíe ❤️",
"Que la suerte te acompañe 🍀",
"Que tus días brillen ✨",
"Que la alegría te inunde 🌈",
"Que el éxito te abrace 🌟",
"Que la paz te envuelva 🕊️",
"Que la salud te proteja 💪",
"Que el amor te encuentre 💘",
"Que la fortuna te bendiga 🎰",
"Que tus sueños se cumplan 💫",
"Que la vida te sonría 😊",
"Que el amor te guarde ❤️",
"Que la suerte te siga 🍀",
"Que tus días sean mágicos ✨",
"Que la alegría te acompañe 🌈",
"Que el éxito sea tuyo 🌟",
"Que la paz te cobije 🕊️",
"Que la salud te bendiga 💪",
"Que el amor te encuentre 💘",
"Que la fortuna te acompañe 🎰",
"Que tus sueños florezcan 🌸",
"Que la vida te ame 💖",
"Que el amor te proteja ❤️",
"Que la suerte te abrace 🍀",
"Que tus días sean perfectos ✨",
"Que la alegría te siga 🌈",
"Que el éxito te corone 👑",
"Que la paz te envuelva 🕊️",
"Que la salud te acompañe 💪",
"Que el amor te guíe siempre 💘",
"Que la fortuna te sonría 🎰",
"Que tus sueños te inspiren 💫",

// === MOMENTOS ESPECIALES (50) ===
"Cada momento contigo es especial ✨",
"Atesorando cada instante juntos 💖",
"Creando recuerdos inolvidables 📸",
"Momentos mágicos a tu lado 🌟",
"Cada segundo es un regalo 🎁",
"Viviendo momentos únicos 💫",
"Compartiendo instantes perfectos 🤗",
"Creando historias juntos 📖",
"Momentos que valen oro 💎",
"Cada día es especial contigo 🌈",
"Atesorando memorias 💭",
"Viviendo momentos mágicos ✨",
"Creando recuerdos eternos 💫",
"Momentos que llenan el alma 💖",
"Cada instante es único 🌟",
"Compartiendo alegría 😊",
"Creando momentos especiales 🎁",
"Viviendo historias únicas 📖",
"Momentos que perduran 💫",
"Cada segundo cuenta ⏰",
"Atesorando sonrisas 😊",
"Viviendo instantes mágicos ✨",
"Creando momentos felices 🌈",
"Momentos que inspiran 💫",
"Cada día es un regalo 🎁",
"Compartiendo amor ❤️",
"Creando recuerdos especiales 📸",
"Viviendo momentos únicos 🌟",
"Momentos que brillan ✨",
"Cada instante es mágico 💫",
"Atesorando abrazos 🤗",
"Viviendo momentos perfectos 💖",
"Creando historias especiales 📖",
"Momentos que llenan 💫",
"Cada segundo es valioso ⏰",
"Compartiendo felicidad 😊",
"Creando momentos únicos 🌟",
"Viviendo instantes especiales ✨",
"Momentos que enamoran ❤️",
"Cada día contigo es especial 🌈",
"Atesorando risas 😄",
"Viviendo momentos mágicos 💫",
"Creando recuerdos únicos 📸",
"Momentos que inspiran 🌟",
"Cada instante es un regalo 🎁",
"Compartiendo amor infinito ❤️",
"Creando momentos eternos ✨",
"Viviendo historias mágicas 📖",
"Momentos que perduran 💫",

// === AMISTAD (50) ===
"Eres una amiga increíble 🤗",
"Tu amistad es un tesoro 💎",
"Gracias por tu amistad sincera 💫",
"Eres una amiga especial ✨",
"Tu amistad ilumina mi vida 🌟",
"Eres una amiga única 💖",
"Tu amistad es un regalo 🎁",
"Gracias por estar siempre 🤝",
"Eres una amiga verdadera ❤️",
"Tu amistad es invaluable 💫",
"Eres una amiga extraordinaria 🌟",
"Tu amistad me hace feliz 😊",
"Gracias por tu apoyo constante 💪",
"Eres una amiga maravillosa ✨",
"Tu amistad es un bendición 🙏",
"Eres una amiga especial 💖",
"Tu amistad es un tesoro 💎",
"Gracias por tu lealtad 🤝",
"Eres una amiga incondicional ❤️",
"Tu amistad es un regalo divino 🎁",
"Eres una amiga única 🌟",
"Tu amistad me inspira 💫",
"Gracias por tu sinceridad 💖",
"Eres una amiga excepcional ✨",
"Tu amistad es un milagro 🙏",
"Eres una amiga verdadera ❤️",
"Tu amistad es un tesoro 💎",
"Gracias por tu compañía 🤗",
"Eres una amiga especial 🌟",
"Tu amistad es un regalo 🎁",
"Eres una amiga extraordinaria 💫",
"Tu amistad me llena de alegría 😊",
"Gracias por tu apoyo 💪",
"Eres una amiga maravillosa ✨",
"Tu amistad es una bendición 🙏",
"Eres una amiga única 💖",
"Tu amistad es invaluable 💎",
"Gracias por tu lealtad eterna 🤝",
"Eres una amiga incondicional ❤️",
"Tu amistad es un regalo divino 🎁",
"Eres una amiga especial 🌟",
"Tu amistad me inspira siempre 💫",
"Gracias por tu sinceridad absoluta 💖",
"Eres una amiga excepcional ✨",
"Tu amistad es un milagro diario 🙏",
"Eres una amiga verdadera ❤️",
"Tu amistad es un tesoro eterno 💎",
"Gracias por tu compañía constante 🤗",
"Eres una amiga única y especial 🌟",
"Tu amistad es un regalo del cielo 🎁",

// === INSPIRACIÓN (50) ===
"Eres una fuente de inspiración 💫",
"Tu luz inspira a todos ✨",
"Eres un ejemplo inspirador 🌟",
"Tu energía motiva 💪",
"Eres una inspiración constante 🎯",
"Tu espíritu inspira 🦋",
"Eres luz que guía ⭐",
"Tu fuerza inspira 💫",
"Eres motivación pura 🔥",
"Tu ejemplo ilumina ✨",
"Eres inspiración diaria 🌟",
"Tu camino inspira 🛤️",
"Eres luz inspiradora 💫",
"Tu valor motiva 💪",
"Eres ejemplo a seguir 👣",
"Tu fortaleza inspira 💫",
"Eres motivación constante 🎯",
"Tu espíritu guía 🦋",
"Eres luz brillante ⭐",
"Tu fuerza motiva 💪",
"Eres inspiración pura 🌟",
"Tu ejemplo guía ✨",
"Eres luz que inspira 💫",
"Tu camino motiva 🛤️",
"Eres inspiración viva 🔥",
"Tu valor inspira 💪",
"Eres ejemplo inspirador 👣",
"Tu fortaleza guía 💫",
"Eres motivación constante 🎯",
"Tu espíritu ilumina 🦋",
"Eres luz que guía ⭐",
"Tu fuerza inspira 💪",
"Eres inspiración diaria 🌟",
"Tu ejemplo motiva ✨",
"Eres luz brillante 💫",
"Tu camino inspira 🛤️",
"Eres motivación pura 🔥",
"Tu valor guía 💪",
"Eres ejemplo a seguir 👣",
"Tu fortaleza ilumina 💫",
"Eres inspiración constante 🎯",
"Tu espíritu motiva 🦋",
"Eres luz que inspira ⭐",
"Tu fuerza guía 💪",
"Eres inspiración viva 🌟",
"Tu ejemplo ilumina ✨",
"Eres luz que motiva 💫",
"Tu camino guía 🛤️",
"Eres inspiración pura 🔥",
"Tu valor ilumina 💪",
  ];
  